name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt-hotspot
        java-version: 11
        cache: gradle
    - name: Build
      run: bash ./gradlew assembleEmbedRelease bundleEmbedNoRecordRelease
    - name: Artifact (Embed AAB w/o recording)
      uses: actions/upload-artifact@v2
      with:
        name: love-android-embed.aab
        path: app/build/outputs/bundle/embedNoRecordRelease/app-embed-noRecord-release.aab
