name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt-hotspot
        java-version: 11
        cache: gradle
    - name: Provide Keystore
      env:
        ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      run: |
        echo $ANDROID_KEYSTORE | base64 --decode > keystore/keystore.zip;
        unzip keystore/keystore.zip -d keystore;
    - name: Build
      run: bash ./gradlew assembleEmbedNoRecordStandaloneRelease bundleEmbedNoRecordGooglePlayRelease
    - name: Artifact (Standalone APK)
      uses: actions/upload-artifact@v2
      with:
        name: liko-android-standalone.apk
        path: app/build/outputs/apk/embedNoRecordStandalone/release/app-embed-noRecord-standalone-release.apk
    - name: Artifact (GooglePlay AAB)
      uses: actions/upload-artifact@v2
      with:
        name: liko-android-googleplay.aab
        path: app/build/outputs/bundle/embedNoRecordGooglePlayRelease/app-embed-noRecord-googlePlay-release.aab
